"""
Gold Standard v6.1: name the components in the 14 reference decompositions
that still said "the first component of X" / "the second component of X".

`build_gold_standard_v6.py` wrote that wording for every ratio-type question
(`synthesis` margins, `ratio_compute`) because it knows the question asks for
a quotient but not what goes into it. `fix_v6_decompositions.py` (2026-09-09)
corrected the 25 rows whose METRIC name was missing; these 14 rows had the
metric but not its components, and passed that script's placeholder check.

Why it matters: Dimension 3 scores whether a chain covers each sub-question.
"Establish the first component of Operating Margin" leaves the judge to
decide what the first component is -- a chain that reads Operating Income and
Net Sales might be marked covered, one that reads Gross Profit might be too.
The 0.98 kappa of the pilot says the ambiguity did not bite there (the reserve
sample holds one of these rows, id 24), but it is cheap to remove and the
column is read by the evaluator only, so no system output changes.

DISCRETIONARY DECISIONS, made explicit as in the earlier fix script
-------------------------------------------------------------------
1. Ratios keep their components. Same principle as id 18 (Debt/Equity): the
   question asks for a quotient the filing does not print as a line item, so
   establishing numerator and denominator are the required sub-questions.
   That includes the Effective Tax Rate (ids 93, 94), which the tax note does
   state directly -- a chain that only quotes that sentence covers neither
   component and is marked incomplete. Deliberate: the FA-2 stratum measures
   cross-section synthesis, and `ratio_compute` is the subtype that says so.

2. id 33 (Amazon International segment profit or loss) is NOT a quotient.
   The segment note reports "International: Operating income (loss)" as one
   figure. Two components were an artefact of the generator's `synthesis`
   handling; the required sub-question is the single lookup. This changes the
   item's completeness denominator from 3 to 1.

Run once, after `fix_v6_decompositions.py`, and not again afterwards:
    uv run python scripts/fix_v6_component_names.py
"""

from __future__ import annotations

import csv
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
GS_DIR = PROJECT_ROOT / "data" / "gold_standard"


def _operating_margin(company: str, year: str) -> list[str]:
    return [
        f"Establish Operating Income for {company} in FY{year}.",
        f"Establish Total Revenue (Net Sales) for {company} in FY{year}.",
        "Compute Operating Margin as Operating Income divided by Total Revenue.",
    ]


FIXES: dict[int, list[str]] = {
    21: _operating_margin("Apple", "2024"),
    22: [
        "Establish Cash Generated by Operating Activities for Apple in FY2024.",
        "Establish Payments for Acquisition of Property, Plant and Equipment "
        "(Capital Expenditures) for Apple in FY2024.",
        "Compute Free Cash Flow as Operating Cash Flow minus Capital Expenditures.",
    ],
    24: _operating_margin("Apple", "2023"),
    26: _operating_margin("Microsoft", "2024"),
    29: _operating_margin("Microsoft", "2023"),
    31: _operating_margin("Amazon", "2024"),
    33: [
        "Establish Operating Income (Loss) of the International segment for "
        "Amazon in FY2024.",
    ],
    34: _operating_margin("Amazon", "2023"),
    36: _operating_margin("Alphabet", "2024"),
    39: _operating_margin("Alphabet", "2023"),
    40: [
        "Establish Total Revenue for Alphabet in FY2022.",
        "Establish the number of employees (headcount) for Alphabet at the end "
        "of FY2022.",
        "Compute revenue per employee as Total Revenue divided by headcount.",
    ],
    93: [
        "Establish Provision for Income Taxes for Apple in FY2024.",
        "Establish Income Before Provision for Income Taxes for Apple in FY2024.",
        "Compute the Effective Tax Rate as Provision for Income Taxes divided by "
        "Income Before Income Taxes.",
    ],
    94: [
        "Establish Provision for Income Taxes for Microsoft in FY2024.",
        "Establish Income Before Income Taxes for Microsoft in FY2024.",
        "Compute the Effective Tax Rate as Provision for Income Taxes divided by "
        "Income Before Income Taxes.",
    ],
    97: [
        "Establish Selling, General and Administrative Expenses for Apple in FY2023.",
        "Establish Total Revenue (Net Sales) for Apple in FY2023.",
        "Compute SG&A Expenses as a percentage of Total Revenue.",
    ],
}


def apply(name: str) -> int:
    path = GS_DIR / name
    with path.open(encoding="utf-8") as fh:
        reader = csv.DictReader(fh, delimiter=";")
        fieldnames = list(reader.fieldnames or [])
        rows = list(reader)

    applied = 0
    for row in rows:
        rid = int(row["id"])
        if rid not in FIXES:
            continue
        current = row.get("reference_decomposition", "")
        if "component" not in current.lower():
            # Already corrected -- the script must be safe to re-run by
            # accident, but it must not silently overwrite a later hand edit.
            continue
        row["reference_decomposition"] = "|".join(FIXES[rid])
        applied += 1

    with path.open("w", newline="", encoding="utf-8") as fh:
        writer = csv.DictWriter(fh, fieldnames=fieldnames, delimiter=";")
        writer.writeheader()
        writer.writerows(rows)
    return applied


def main() -> int:
    # HISTORICAL -- version literals pinned on purpose, as in
    # fix_v6_decompositions.py: these corrections belong to v6 alone.
    for name in ("gold_standard_v6_en.csv", "gold_standard_v6.csv"):
        print(f"{apply(name)} Korrekturen in {name}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
